services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pump
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pump"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pump
      WEBSOCKET_URL: wss://pumpportal.fun/api/data
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
